#! /usr/bin/env python

from sys import argv
import client
import server


usage = '''start server, connect clients

server default: port=51515, backlog=10
client default: host=localhost, port=51515, user=userX
set buffer in client/server.py, default 4096

examples:
pychat server <port>
pychat client <host-ip> <port> <username>'''


if argv[1] == 'server':
    try:
        server.ChatServer(port=argv[2])
    except IndexError:
        server.ChatServer()

elif argv[1] == 'client':
    try:
        client.ChatClient(host=argv[2], port=argv[3], user=argv[4])
    except IndexError:
        client.ChatClient()

elif argv[1] == '-h':
    print(usage)
