#! /usr/bin/env python

import sys
import client
import server

if sys.argv[1] == 'server' and sys.argv[2] == 'start':
	server = server.ChatServer()
	server.start()
	server.client_handler()

elif sys.argv[1] == 'client' and sys.argv[2] == 'start':
	username = input('username: ')
	client = client.ChatClient(user=username)
	client.start()	
